# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

name: '[CI/CD] CD Pipeline'
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
# Remove all permissions by default.
permissions:
  contents: write
jobs:
  update-index:
    runs-on: ubuntu-latest
    name: Update charts index
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          path: ~/artifacts
      # If we perform a checkout of the main branch, we will find conflicts with the submodules
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
        with:
          ref: 'index'
          path: index
          token: ${{ secrets.BITNAMI_BOT_TOKEN }}
      - name: Install helm
        run: |
          HELM_TARBALL="helm-v3.8.1-linux-amd64.tar.gz"
          curl -SsLfO "https://get.helm.sh/${HELM_TARBALL}" && sudo tar xf "$HELM_TARBALL" --strip-components 1 -C /usr/local/bin
      - id: update-index
        name: Fetch chart and update index
        run: |
          # Download published asset
          mkdir download
          curl -LJO --output-dir download/ https://charts.bitnami.com/bitnami/argo-workflows-8.0.9.tgz

          cd index
          git config user.name "Bitnami Containers"
          git config user.email "bitnami-bot@vmware.com"

          attempts=0
          max_attempts=5
          is_index_updated=0
          while [[ $attempts -lt $max_attempts && $is_index_updated -eq 0 ]]; do
            attempts=$((attempts + 1))
            git fetch origin index
            git reset --hard origin/index

            # Rebuild index
            helm repo index --url https://charts.bitnami.com/bitnami --merge bitnami/index.yaml ../download
            cp ../download/index.yaml bitnami/index.yaml
            # Push changes
            git add bitnami/index.yaml && git commit -m "Update index.yaml" -s
            git push && is_index_updated=1 || echo "Failed to push during attempt $attempts"
          done

          # Temporary code to confirm index is not broken
          attempts=0
          is_index_test_updated=0
          while [[ $attempts -lt $max_attempts && $is_index_test_updated -eq 0 ]]; do
            attempts=$((attempts + 1))

            # Pull changes from remote
            git fetch origin index-test
            current_commit_id=$(git rev-parse origin/index-test)
            git reset --hard $(git commit-tree origin/index-test^{tree} -m "Update index.yaml")

            # Rebuild index
            helm repo index --url https://charts.bitnami.com/bitnami --merge bitnami/index.yaml ../download
            cp ../download/index.yaml bitnami/index.yaml

            # Push changes
            git add bitnami/index.yaml && git commit --signoff --amend --no-edit
            git push origin index:index-test --force-with-lease=index-test:${current_commit_id} && is_index_updated=1 || echo "Failed to push during attempt $attempts"
          done

          if [[ $is_index_updated -ne 1 ]]; then
            echo "Could not update the index after $max_attempts attempts"
            exit 1
          fi
